
// This file has been generated by the GUI designer. Do not modify.
namespace Melody
{
	public partial class fParam
	{
		private global::Gtk.VBox vbox5;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.ComboBox cmbBoxCurrentSong;
		
		private global::Gtk.Button btnLoad;
		
		private global::Gtk.Button btnClear;
		
		private global::Gtk.Button btnPlay;
		
		private global::Gtk.CheckButton chckBtnSubFolders;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView treeview1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Melody.fParam
			this.Name = "Melody.fParam";
			this.Title = global::Mono.Unix.Catalog.GetString ("Параметры программы");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Melody.fParam.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.cmbBoxCurrentSong = global::Gtk.ComboBox.NewText ();
			this.cmbBoxCurrentSong.Name = "cmbBoxCurrentSong";
			this.hbox3.Add (this.cmbBoxCurrentSong);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.cmbBoxCurrentSong]));
			w1.Position = 0;
			w1.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.btnLoad = new global::Gtk.Button ();
			this.btnLoad.CanFocus = true;
			this.btnLoad.Name = "btnLoad";
			this.btnLoad.UseUnderline = true;
			this.btnLoad.Label = global::Mono.Unix.Catalog.GetString ("Загрузить");
			this.hbox3.Add (this.btnLoad);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.btnLoad]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.btnClear = new global::Gtk.Button ();
			this.btnClear.CanFocus = true;
			this.btnClear.Name = "btnClear";
			this.btnClear.UseUnderline = true;
			this.btnClear.Label = global::Mono.Unix.Catalog.GetString ("Очистить");
			this.hbox3.Add (this.btnClear);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.btnClear]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.btnPlay = new global::Gtk.Button ();
			this.btnPlay.CanFocus = true;
			this.btnPlay.Name = "btnPlay";
			this.btnPlay.UseUnderline = true;
			this.btnPlay.Label = global::Mono.Unix.Catalog.GetString ("Играть");
			this.hbox3.Add (this.btnPlay);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.btnPlay]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.chckBtnSubFolders = new global::Gtk.CheckButton ();
			this.chckBtnSubFolders.CanFocus = true;
			this.chckBtnSubFolders.Name = "chckBtnSubFolders";
			this.chckBtnSubFolders.Label = global::Mono.Unix.Catalog.GetString ("Смотреть подпапки");
			this.chckBtnSubFolders.DrawIndicator = true;
			this.chckBtnSubFolders.UseUnderline = true;
			this.hbox3.Add (this.chckBtnSubFolders);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.chckBtnSubFolders]));
			w5.PackType = ((global::Gtk.PackType)(1));
			w5.Position = 4;
			this.vbox5.Add (this.hbox3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox3]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview1 = new global::Gtk.TreeView ();
			this.treeview1.CanFocus = true;
			this.treeview1.Name = "treeview1";
			this.GtkScrolledWindow.Add (this.treeview1);
			this.vbox5.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.GtkScrolledWindow]));
			w8.Position = 1;
			this.Add (this.vbox5);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 615;
			this.DefaultHeight = 338;
			this.Show ();
		}
	}
}
